# Generated by Django 5.0.6 on 2024-07-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_remove_log_owner_mailing_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [("can_view_mailings", "can view mailings")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
